name: 30K Radar Bot

on:
  schedule:
    - cron: "0 14 * * *"  # 21:00 VN
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python radar.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          

      - name: Commit state
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add sent.json
          git commit -m "update sent repos" || echo "no changes"
          git push
